### ISSUE TITLE
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.io.audio#3]
I am having a very strange error when building `bob.io.audio`:

```python
import: 'bob.io.audio'
Traceback (most recent call last):
  File "/home/amir/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 31, in <module>
    import bob.io.audio
  File "/home/amir/miniconda3/envs/_test/lib/python3.5/site-packages/bob.io.audio-2.0.0-py3.5-linux-x86_64.egg/bob/io/audio/__init__.py", line 4, in <module>
    from ._library import *
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```

I have `libpng16.so.0` installed but why is it trying to import libpng?
Here is the full log:
[log.txt](https://github.com/bioidiap/bob.io.audio/files/161156/log.txt)

**Comment by 183amir** [comment]
I found something:

```
ldd ~/miniconda3/envs/_test/lib/libsox.so.3                                                                                                                    :(
	linux-vdso.so.1 (0x00007ffcc4dee000)
	libltdl.so.7 => /usr/lib/libltdl.so.7 (0x00007f42ad505000)
	libpng12.so.0 => not found
	libz.so.1 => /home/amir/miniconda3/envs/_test/lib/./libz.so.1 (0x00007f42ad2ef000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f42acfe9000)
	libgomp.so.1 => /home/amir/miniconda3/envs/_test/lib/./libgomp.so.1 (0x00007f42acdda000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f42acbbd000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f42ac81b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f42ac617000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00005606e7687000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f42ac40f000)
```

**Comment by anjos** [comment]
Some googling reveals: https://bugs.archlinux.org/task/19795

**Comment by 183amir** [comment]
It's not about ArchLinux. Sox depends on libpng and we need to provide it when building it in conda.
Fixed!
